var bbsePopup_dictionary=new Array();
bbsePopup_dictionary['ja'] = { 
	"Please select a bulk actions."  : "一括作業を選択してください。    ",
	"All popups in trash will be deleted.\nEmpty trash?" : "ゴミ箱内の全てのポップアップが削除されます。\nゴミ箱を空にしますか？",
	"Select popup to execute batch work."  : "一括作業を実行するポップアップを選択してください。    ",
	"Change selected popup to 'Active'?"  : "選択したポップアップを＇使用する＇状態に変更しますか?    ",
	"Change selected popup to 'Inactive'?"  : "選択したポップアップを＇使用しない＇状態に変更しますか?    ",
	"Restore selected popup?" : "選択したポップアップを復旧しますか？     ",
	"Move selected popup to 'Trash'?"  : "選択したポップアップを＇ゴミ箱＇に移動しますか？    ",
	"Delete selected popup permanently?"  : "選択したポップアップを永久的に削除しますか?    ",
	"Move this popup to 'trash'?"  : "該当のポップアップを＇ゴミ箱＇に移動しますか？    ",
	"Restore this popup?" : "該当のポップアップを復旧しますか？    ",
	"Delete this popup permanently?" :"該当のポップアップを永久的に削除しますか?    ",
	"Popup copy completed.\nUse after changing status of popup." : "ポップアップのコピーを完了しました。    \nポップアップの状態を変更したあとに利用してください。   ",		
	"Save %s?"  : "'%s'を保存しますか？    ",
	"Initialize %s?"  : "'%s'を初期化しますか？    ",
	"Add"  : "追加",
	"Update"  : "修正",
	"Enter popup title."  : "ポップアップの題目を入力してください。     ",
	"Enter popup alias."  : "ポップアップのエイリアス（別名）を入力してください。      ",
	"Enter alias with blank spaces." : "エイリアス（別名）を入力してください。（すみなく）      ",
	"Enter popup size (Width)."  : "ポップアップのサイズ（横）を入力してください。     ",
	"Enter popup size (Height)."  : "ポップアップのサイズ（縦）を入力してください。     ",
	"Enter popup period."  : "ポップアップの期間を入力してください。     ",
	"Enter popup end date later or the same as the start date." : "ポップアップの終了日時をスタート日時と同じか、後日に入力してください。入力してください。",
	"Enter popup background color." : "ポップアップのバックカラーを入力してください。     ",
	"Select popup border color."  : "ポップアップの枠線のカラーを選択してください。     ",
	"Enter popup contents."  : "ポップアップの内容を入力してください。     ",
	"%s for popup?"  : "ポップアップを%sしますか？       ",
	"Added popup."  : "ポップアップの追加を完了しました。       ",
	"Edited popup."  : "ポップアップの修正を完了しました。       ",
	"Error occurred while saving DB."  : "DB保存中にエラーが発生しました。        ",
	"Failed to connect to server."  : "サーバーとの通信に失敗しました。         ",
	"'%s' alias already exists."  : "'%s'はすでに既に存在しているエイリアス（別名）です。         ",
	"Popup does not exist."  : "ポップアップが存在しません。       ",
	"Ok"  : "確認",
	"Cancel"  : "取り消し"
};

bbsePopup_dictionary['ja-JP'] = { 
	"Please select a bulk actions."  : "一括作業を選択してください。    ",
	"All popups in trash will be deleted.\nEmpty trash?" : "ゴミ箱内の全てのポップアップが削除されます。\nゴミ箱を空にしますか？",
	"Select popup to execute batch work."  : "一括作業を実行するポップアップを選択してください。    ",
	"Change selected popup to 'Active'?"  : "選択したポップアップを＇使用する＇状態に変更しますか?    ",
	"Change selected popup to 'Inactive'?"  : "選択したポップアップを＇使用しない＇状態に変更しますか?    ",
	"Restore selected popup?" : "選択したポップアップを復旧しますか？     ",
	"Move selected popup to 'Trash'?"  : "選択したポップアップを＇ゴミ箱＇に移動しますか？    ",
	"Delete selected popup permanently?"  : "選択したポップアップを永久的に削除しますか?    ",
	"Move this popup to 'trash'?"  : "該当のポップアップを＇ゴミ箱＇に移動しますか？    ",
	"Restore this popup?" : "該当のポップアップを復旧しますか？    ",
	"Delete this popup permanently?" :"該当のポップアップを永久的に削除しますか?    ",
	"Popup copy completed.\nUse after changing status of popup." : "ポップアップのコピーを完了しました。    \nポップアップの状態を変更したあとに利用してください。   ",		
	"Save %s?"  : "'%s'を保存しますか？    ",
	"Initialize %s?"  : "'%s'を初期化しますか？    ",
	"Add"  : "追加",
	"Update"  : "修正",
	"Enter popup title."  : "ポップアップの題目を入力してください。     ",
	"Enter popup alias."  : "ポップアップのエイリアス（別名）を入力してください。      ",
	"Enter alias with blank spaces." : "エイリアス（別名）を入力してください。（すみなく）      ",
	"Enter popup size (Width)."  : "ポップアップのサイズ（横）を入力してください。     ",
	"Enter popup size (Height)."  : "ポップアップのサイズ（縦）を入力してください。     ",
	"Enter popup period."  : "ポップアップの期間を入力してください。     ",
	"Enter popup end date later or the same as the start date." : "ポップアップの終了日時をスタート日時と同じか、後日に入力してください。入力してください。",
	"Enter popup background color." : "ポップアップのバックカラーを入力してください。     ",
	"Select popup border color."  : "ポップアップの枠線のカラーを選択してください。     ",
	"Enter popup contents."  : "ポップアップの内容を入力してください。     ",
	"%s for popup?"  : "ポップアップを%sしますか？       ",
	"Added popup."  : "ポップアップの追加を完了しました。       ",
	"Edited popup."  : "ポップアップの修正を完了しました。       ",
	"Error occurred while saving DB."  : "DB保存中にエラーが発生しました。        ",
	"Failed to connect to server."  : "サーバーとの通信に失敗しました。         ",
	"'%s' alias already exists."  : "'%s'はすでに既に存在しているエイリアス（別名）です。         ",
	"Popup does not exist."  : "ポップアップが存在しません。       ",
	"Ok"  : "確認",
	"Cancel"  : "取り消し"
};

bbsePopup_dictionary['ko-KR'] = { 
	"Please select a bulk actions."  : "일괄작업을 선택해 주세요.    ",
	"All popups in trash will be deleted.\nEmpty trash?" : "휴지통의 모든 팝업이 삭제됩니다.\n휴지통 비우기를 실행하시겠습니까?",
	"Select popup to execute batch work."  : "일괄 작업을 실행 할 팝업을 선택해주세요.    ",
	"Change selected popup to 'Active'?"  : "선택한 팝업을 '사용함' 상태로 변경하시겠습니까?    ",
	"Change selected popup to 'Inactive'?"  : "선택한 팝업을 '사용안함' 상태로 변경하시겠습니까?    ",
	"Restore selected popup?" : "선택한 팝업을 복구하시겠습니까?",
	"Move selected popup to 'Trash'?"  : "선택한 팝업을 '휴지통'으로 이동하시겠습니까?    ",
	"Delete selected popup permanently?"  : "선택한 팝업을 영구적으로 삭제하시겠습니까?    ",
	"Move this popup to 'trash'?"  : "해당 팝업을 '휴지통'으로 이동하시겠습니까?    ",
	"Restore this popup?" : "해당 팝업을 복구하시겠습니까?    ",
	"Delete this popup permanently?" :"해당 팝업을 영구적으로 삭제하시겠습니까?    ",
	"Popup copy completed.\nUse after changing status of popup." : "팝업 복사를 완료하였습니다.    \n팝업의 상태를 변경하신 후 이용해주세요.   ",		
	"Save %s?"  : "%s을(를) 저장 하시겠습니까?    ",
	"Initialize %s?"  : "%s을(를) 초기화 하시겠습니까?    ",
	"Add"  : "추가",
	"Update"  : "수정",
	"Enter popup title."  : "팝업 제목을 입력해 주세요.     ",
	"Enter popup alias."  : "팝업 별칭을 입력해 주세요.      ",
	"Enter alias with blank spaces." : "별칭을 공백없이 입력해 주세요.      ",
	"Enter popup size (Width)."  : "팝업 크기(가로)를 입력해 주세요.     ",
	"Enter popup size (Height)."  : "팝업 크기(세로)를 입력해 주세요.     ",
	"Enter popup period."  : "팝업 기간을 입력해 주세요.     ",
	"Enter popup end date later or the same as the start date." : "팝업 종료일을 시작일보다 크거나 같게 입력해주세요.",
	"Enter popup background color." : "팝업의 배경색을 입력해 주세요.     ",
	"Select popup border color."  : "팝업 테두리 색상을 선택해 주세요.     ",
	"Enter popup contents."  : "팝업 내용을 입력해 주세요.      ",
	"%s for popup?"  : "팝업을 %s 하시겠습니까?       ",
	"Added popup."  : "팝업 추가를 완료하였습니다.       ",
	"Edited popup."  : "팝업 수정을 완료하였습니다.       ",
	"Error occurred while saving DB."  : "DB 저장 중 에러가 발생하였습니다.        ",
	"Failed to connect to server."  : "서버와의 통신이 실패했습니다.         ",
	"'%s' alias already exists."  : "'%s' 은(는) 이미 존재하는 Alias 입니다.         ",
	"Popup does not exist."  : "팝업이 존재하지 않습니다.       ",
	"Ok"  : "확인",
	"Cancel"  : "취소"
};


bbsePopup_dictionary['zh-CN'] = { 
	"Please select a bulk actions."  : "请选择批量作业。    ",
	"All popups in trash will be deleted.\nEmpty trash?" : "垃圾桶的所有弹窗将删除。\n是否清空垃圾桶？",
	"Select popup to execute batch work."  : "请选择要进行批量作业的弹窗。    ",
	"Change selected popup to 'Active'?"  : "是否将选择的弹窗状态变更为‘激活’？    ",
	"Change selected popup to 'Inactive'?"  : "是否将选择的弹窗状态变更为‘非激活’？    ",
	"Restore selected popup?" : "是否恢复选择的弹窗？",
	"Move selected popup to 'Trash'?"  : "是否将选择的弹窗移动到‘垃圾桶’？    ",
	"Delete selected popup permanently?"  : "是否将选择的弹窗永久删除？    ",
	"Move this popup to 'trash'?"  : "是否将该弹窗移动到‘垃圾桶’？    ",
	"Restore this popup?" : "是否将该弹窗恢复？    ",
	"Delete this popup permanently?" :"是否将该弹窗永久删除？    ",
	"Popup copy completed.\nUse after changing status of popup." : "复制弹窗已完成。    \n请将弹窗状态变更后使用。   ",		
	"Save %s?"  : "是否储存%s？    ",
	"Initialize %s?"  : "是否初始化%s？    ",
	"Add"  : "增加",
	"Update"  : "修整",
	"Enter popup title."  : "请输入弹窗题目。     ",
	"Enter popup alias."  : "请输入弹窗别称。      ",
	"Enter alias with blank spaces." : "请将别称无空格输入。      ",
	"Enter popup size (Width)."  : "请输入弹窗大小（宽）。     ",
	"Enter popup size (Height)."  : "请输入弹窗大小（长）。     ",
	"Enter popup period."  : "请输入弹窗期间。     ",
	"Enter popup end date later or the same as the start date." : "请输入大于或等于起始日期的弹窗终了日期。",
	"Enter popup background color." : "请输入弹窗背景色。     ",
	"Select popup border color."  : "请选择弹窗边框色。     ",
	"Enter popup contents."  : "请输入弹窗内容。      ",
	"%s for popup?"  : "是否将弹窗%s？       ",
	"Added popup."  : "增加弹窗已完成。       ",
	"Edited popup."  : "修改弹窗已完成。       ",
	"Error occurred while saving DB."  : "储存DB时发生错误。        ",
	"Failed to connect to server."  : "与服务器的通信失败。         ",
	"'%s' alias already exists."  : "‘%s’的别称已存在。         ",
	"Popup does not exist."  : "弹窗不存在。       ",
	"Ok"  : "确认",
	"Cancel"  : "取消"
};
